const words = {
  greetings: [
    {
      src: 'greetings/seeyoulater',
      wordAi: 'See you later!',
      transcription: '',
      wordUa: 'Побачимося пізніше!',
    },
    {
      src: 'greetings/bye',
      wordAi: 'Bye!',
      transcription: '',
      wordUa: 'Бувай!',
    },
    {
      src: 'greetings/goodbye',
      wordAi: 'Goodbye!',
      transcription: '',
      wordUa: 'До побачення!',
    },
    {
      src: 'greetings/nicetomeetyoutoo',
      wordAi: 'Nice to meet you, too!',
      transcription: '',
      wordUa: 'Також приємно познайомитись!',
    },
    {
      src: 'greetings/nicetomeetyou',
      wordAi: 'Nice to meet you!',
      transcription: '',
      wordUa: 'Приємно познайомитись!',
    },
    {
      src: 'greetings/thisismyfriend',
      wordAi: 'This is my friend',
      transcription: '',
      wordUa: 'Це мій друг ...',
    },
    {
      src: 'greetings/mynameisivan',
      wordAi: 'My name is Ivan',
      transcription: '',
      wordUa: "Мене звати Іван / Моє ім'я Іван",
    },
    {
      src: 'greetings/whatshername',
      wordAi: "What's her name?",
      transcription: '',
      wordUa: 'Як її звати?',
    },
    {
      src: 'greetings/whatshisname',
      wordAi: "What's his name?",
      transcription: '',
      wordUa: 'Як його звати?',
    },
    {
      src: 'greetings/whatsyourname',
      wordAi: "What's your name?",
      transcription: '',
      wordUa: 'Як вас звати?',
    },
    {
      src: 'greetings/verywellthankyou',
      wordAi: 'Very well, thank you.',
      transcription: '',
      wordUa: 'Дуже добре, дякую.',
    },
    {
      src: 'greetings/finethanksandyou',
      wordAi: 'Fine, thanks. And you?',
      transcription: '',
      wordUa: 'Все гаразд, дякую!',
    },
    {
      src: 'greetings/imokthankyou',
      wordAi: "I'm OK, thank you!",
      transcription: '',
      wordUa: 'Все гаразд, дякую!',
    },
    {
      src: 'greetings/howareyou',
      wordAi: 'How are you?',
      transcription: '',
      wordUa: 'Як справи?',
    },
    {
      src: 'greetings/hi',
      wordAi: 'Hi!',
      transcription: '|haɪ|',
      wordUa: 'Привіт!',
    },
    {
      src: 'greetings/hello',
      wordAi: 'Hello!',
      transcription: '|həˈləʊ|',
      wordUa: 'Привіт!',
    },
  ],
  numbers: [
    {
      src: 'numbers/one',
      wordAi: 'one',
      transcription: '|wʌn|',
      wordUa: '1',
    },
    {
      src: 'numbers/two',
      wordAi: 'two',
      transcription: '|tuː|',
      wordUa: '2',
    },
    {
      src: 'numbers/three',
      wordAi: 'three',
      transcription: '|θriː|',
      wordUa: '3',
    },
    {
      src: 'numbers/four',
      wordAi: 'four',
      transcription: '|fɔː|',
      wordUa: '4',
    },
    {
      src: 'numbers/five',
      wordAi: 'five',
      transcription: '|faɪv|',
      wordUa: '5',
    },
    {
      src: 'numbers/six',
      wordAi: 'six',
      transcription: '|sɪks|',
      wordUa: '6',
    },
    {
      src: 'numbers/seven',
      wordAi: 'seven',
      transcription: '|ˈsev(ə)n|',
      wordUa: '7',
    },
    {
      src: 'numbers/eight',
      wordAi: 'eight',
      transcription: '|eɪt|',
      wordUa: '8',
    },
    {
      src: 'numbers/nine',
      wordAi: 'nine',
      transcription: '|naɪn|',
      wordUa: '9',
    },
    {
      src: 'numbers/ten',
      wordAi: 'ten',
      transcription: '|ten|',
      wordUa: '10',
    },

    {
      src: 'numbers/eleven',
      wordAi: 'eleven',
      transcription: '|ɪˈlev(ə)n|',
      wordUa: '11',
    },
    {
      src: 'numbers/twelve',
      wordAi: 'twelve',
      transcription: '|twelv|',
      wordUa: '12',
    },
    {
      src: 'numbers/thirteen',
      wordAi: 'thirteen',
      transcription: '|θɜːˈtiːn|',
      wordUa: '13',
    },
    {
      src: 'numbers/fourteen',
      wordAi: 'fourteen',
      transcription: '|fɔːˈtiːn|',
      wordUa: '14',
    },
    {
      src: 'numbers/fifteen',
      wordAi: 'fifteen',
      transcription: '|fɪfˈtiːn|',
      wordUa: '15',
    },
    {
      src: 'numbers/sixteen',
      wordAi: 'sixteen',
      transcription: '|sɪksˈtiːn|',
      wordUa: '16',
    },
    {
      src: 'numbers/seventeen',
      wordAi: 'seventeen',
      transcription: '|sev(ə)nˈtiːn|',
      wordUa: '17',
    },
    {
      src: 'numbers/eighteen',
      wordAi: 'eighteen',
      transcription: '|eɪˈtiːn|',
      wordUa: '18',
    },
    {
      src: 'numbers/nineteen',
      wordAi: 'nineteen',
      transcription: '|naɪnˈtiːn|',
      wordUa: '19',
    },
    {
      src: 'numbers/twenty',
      wordAi: 'twenty',
      transcription: '|ˈtwentɪ|',
      wordUa: '20',
    },
    {
      src: 'numbers/thirty',
      wordAi: 'thirty',
      transcription: '|ˈθɜːtɪ|',
      wordUa: '30',
    },
    {
      src: 'numbers/forty',
      wordAi: 'forty',
      transcription: '|ˈfɔːtɪ|',
      wordUa: '40',
    },
    {
      src: 'numbers/fifty',
      wordAi: 'fifty',
      transcription: '|ˈfɪftɪ|',
      wordUa: '50',
    },
    {
      src: 'numbers/sixty',
      wordAi: 'sixty',
      transcription: '|ˈsɪkstɪ|',
      wordUa: '60',
    },
    {
      src: 'numbers/seventy',
      wordAi: 'seventy',
      transcription: '|ˈsev(ə)ntɪ|',
      wordUa: '70',
    },
    {
      src: 'numbers/eighty',
      wordAi: 'eighty',
      transcription: '|ˈeɪtɪ|',
      wordUa: '80',
    },
    {
      src: 'numbers/ninety',
      wordAi: 'ninety',
      transcription: '|ˈnaɪntɪ|',
      wordUa: '90',
    },
    {
      src: 'numbers/onehundred',
      wordAi: 'one hundred',
      transcription: '|wʌn| |ˈhʌndrəd|',
      wordUa: '100',
    },
  ],
  countries_and_nationality: [
    {
      src: 'countries_and_nationality/china',
      wordAi: 'China',
      transcription: '| ˈtʃaɪnə |',
      wordUa: 'Китай',
    },
    {
      src: 'countries_and_nationality/chinese',
      wordAi: 'Chinese',
      transcription: '| ˌtʃaɪˈniːz |',
      wordUa: 'китаєць, китаянка',
    },

    {
      src: 'countries_and_nationality/turkey',
      wordAi: 'Turkey',
      transcription: '| ˈtɜːkɪ |',
      wordUa: 'Туреччина',
    },
    {
      src: 'countries_and_nationality/turkish',
      wordAi: 'Turkish',
      transcription: '| ˈtɜːkɪʃ |',
      wordUa: 'турок, турчанка',
    },

    {
      src: 'countries_and_nationality/theusa',
      wordAi: 'the USA',
      transcription: '--',
      wordUa: 'США',
    },
    {
      src: 'countries_and_nationality/american',
      wordAi: 'American',
      transcription: '| əˈmerɪk(ə)n |',
      wordUa: 'американець, американка',
    },

    {
      src: 'countries_and_nationality/spain',
      wordAi: 'Spain',
      transcription: '|speɪn|',
      wordUa: 'Іспанія',
    },
    {
      src: 'countries_and_nationality/spanish',
      wordAi: 'Spanish',
      transcription: '|ˈspænɪʃ|',
      wordUa: 'іспанець, іспанка',
    },

    {
      src: 'countries_and_nationality/italy',
      wordAi: 'Italy',
      transcription: '|ˈɪtəlɪ|',
      wordUa: 'Італія',
    },
    {
      src: 'countries_and_nationality/italian',
      wordAi: 'Italian',
      transcription: '|ɪˈtæljən|',
      wordUa: 'італієць, італійка',
    },

    {
      src: 'countries_and_nationality/germany',
      wordAi: 'Germany',
      transcription: '|ˈdʒɜːmənɪ|',
      wordUa: 'Німеччина',
    },
    {
      src: 'countries_and_nationality/german',
      wordAi: 'German',
      transcription: '|ˈdʒɜːmən|',
      wordUa: 'німець, німкеня',
    },
    {
      src: 'countries_and_nationality/france',
      wordAi: 'France',
      transcription: '|frɑːns|',
      wordUa: 'Франція',
    },
    {
      src: 'countries_and_nationality/french',
      wordAi: 'French',
      transcription: '|fren(t)ʃ|',
      wordUa: 'Француженка, Француз',
    },
    {
      src: 'countries_and_nationality/canada',
      wordAi: 'Canada',
      transcription: '|ˈkanədə|',
      wordUa: 'Канада',
    },
    {
      src: 'countries_and_nationality/canadian',
      wordAi: 'Canadian',
      transcription: '|kəˈneɪdɪən|',
      wordUa: 'канадець, канадка',
    },
    {
      src: 'countries_and_nationality/poland',
      wordAi: 'Poland',
      transcription: '|ˈpəʊlənd|',
      wordUa: 'Польща',
    },
    {
      src: 'countries_and_nationality/polish',
      wordAi: 'Polish',
      transcription: '|ˈpɒlɪʃ|',
      wordUa: 'поляк, полячка',
    },
    {
      src: 'countries_and_nationality/ukraine',
      wordAi: 'Ukraine',
      transcription: '|juːˈkreɪn|',
      wordUa: 'Україна',
    },
    {
      src: 'countries_and_nationality/ukrainian',
      wordAi: 'Ukrainian',
      transcription: '|juːˈkreɪnɪən|',
      wordUa: 'українець, українка',
    },
    {
      src: 'countries_and_nationality/theuk',
      wordAi: 'the UK',
      transcription: '--',
      wordUa: 'Велика Британія',
    },
    {
      src: 'countries_and_nationality/british',
      wordAi: 'British',
      transcription: '|ˈbrɪtɪʃ|',
      wordUa: 'британець, британка',
    },
  ],
  family: [
    {
      src: 'family/parents',
      wordAi: 'parents',
      transcription: '| ˈpeərənts |',
      wordUa: 'батьки',
    },
    {
      src: 'family/wife',
      wordAi: 'wife',
      transcription: '| waɪf |',
      wordUa: 'дружина',
    },
    {
      src: 'family/sister',
      wordAi: 'sister',
      transcription: '| ˈsɪstə |',
      wordUa: 'сестра',
    },
    {
      src: 'family/brother',
      wordAi: 'brother',
      transcription: '| ˈbrʌðə |',
      wordUa: 'брат',
    },
    {
      src: 'family/daughter',
      wordAi: 'daughter',
      transcription: '| ˈdɔːtə |',
      wordUa: 'дочка',
    },
    {
      src: 'family/son',
      wordAi: 'son',
      transcription: '| sʌn |',
      wordUa: 'син',
    },
    {
      src: 'family/mother',
      wordAi: 'mother',
      transcription: '| ˈmʌðə |',
      wordUa: 'мама',
    },
    {
      src: 'family/father',
      wordAi: 'father',
      transcription: '| ˈfɑːðə |',
      wordUa: 'батько',
    },
    {
      src: 'family/husband',
      wordAi: 'husband',
      transcription: '| ˈhʌzbənd |',
      wordUa: 'чоловік',
    },
  ],
  job: [
    {
      src: 'job/waiter',
      wordAi: 'waiter',
      transcription: '| ˈweɪtə |',
      wordUa: 'офіціант',
    },
    {
      src: 'job/actor',
      wordAi: 'actor',
      transcription: '| ˈæktə |',
      wordUa: 'актор',
    },
    {
      src: 'job/taxidriver',
      wordAi: 'taxi driver',
      transcription: '| ˈtæksɪ | | ˈdraɪvər |',
      wordUa: 'водій таксі',
    },
    {
      src: 'job/singer',
      wordAi: 'singer',
      transcription: '| ˈsɪŋə |',
      wordUa: 'співачка, співак',
    },
    {
      src: 'job/engineer',
      wordAi: 'engineer',
      transcription: '| endʒɪˈnɪə |',
      wordUa: 'інженер',
    },
    {
      src: 'job/doctor',
      wordAi: 'doctor',
      transcription: '| ˈdɒktə |',
      wordUa: 'лікар',
    },
    {
      src: 'job/businesswoman',
      wordAi: 'businesswoman',
      transcription: '| ˈbɪznəswʊmən |',
      wordUa: 'жінка-підприємець',
    },
    {
      src: 'job/businessman',
      wordAi: 'businessman',
      transcription: '| ˈbɪznɪsmən |',
      wordUa: 'бізнесмен',
    },
    {
      src: 'job/teacher',
      wordAi: 'teacher',
      transcription: '| ˈtiːtʃə |',
      wordUa: 'вчитель',
    },
    { src: 'job/job', wordAi: 'job', transcription: '', wordUa: 'робота' },
    { src: 'job/accountant', wordAi: 'accountant', transcription: '', wordUa: 'бухгалтер' },
    { src: 'job/architect', wordAi: 'architect', transcription: '', wordUa: 'архітектор' },
    { src: 'job/artist', wordAi: 'artist', transcription: '', wordUa: 'митець, художник' },
    { src: 'job/driver', wordAi: 'driver', transcription: '', wordUa: 'водій' },
    { src: 'job/firefighter', wordAi: 'firefighter', transcription: '', wordUa: 'вогнеборець' },
    { src: 'job/hairdresser', wordAi: 'hairdresser', transcription: '', wordUa: 'перукар' },
    { src: 'job/journalist', wordAi: 'journalist', transcription: '', wordUa: 'журналіст' },
    { src: 'job/lawyer', wordAi: 'lawyer', transcription: '', wordUa: 'юрист, правознавець' },
    { src: 'job/manager', wordAi: 'manager', transcription: '', wordUa: 'менеджер' },
    { src: 'job/nurse', wordAi: 'nurse', transcription: '', wordUa: 'медсестра, медбрат' },
    {
      src: 'job/policeofficer',
      wordAi: 'police officer',
      transcription: '',
      wordUa: 'поліцейський',
    },
    { src: 'job/programmer', wordAi: 'programmer', transcription: '', wordUa: 'програміст' },
    {
      src: 'job/shopassistant',
      wordAi: 'shop assistant',
      transcription: '',
      wordUa: 'продавець',
    },
  ],
  words_1: [
    {
      src: 'words_1/married',
      wordAi: 'married',
      transcription: '|ˈmærɪd|',
      wordUa: 'одружений, заміжня',
    },
    {
      src: 'words_1/colour',
      wordAi: 'colour',
      transcription: '|ˈkʌlə|',
      wordUa: 'колір',
    },
    {
      src: 'words_1/violin',
      wordAi: 'violin',
      transcription: '|vaɪəˈlɪn|',
      wordUa: 'скрипка',
    },
    {
      src: 'words_1/mobilephone',
      wordAi: 'mobile phone',
      transcription: '| ˈməʊbaɪl | |fəʊn|',
      wordUa: 'мобільний телефон',
    },
    {
      src: 'words_1/student',
      wordAi: 'student',
      transcription: '| ˈstjuːd(ə)nt |',
      wordUa: 'студент, студентка',
    },
    {
      src: 'words_1/kid',
      wordAi: 'kid',
      transcription: '| kɪd |',
      wordUa: 'дитина',
    },
    {
      src: 'words_1/friend',
      wordAi: 'friend',
      transcription: '| frend |',
      wordUa: 'друг, подруга',
    },
    {
      src: 'words_1/dog',
      wordAi: 'dog',
      transcription: '| dɒɡ |',
      wordUa: 'собака',
    },
    {
      src: 'words_1/cat',
      wordAi: 'cat',
      transcription: '| kæt |',
      wordUa: 'кіт, кішка',
    },
    {
      src: 'words_1/woman',
      wordAi: 'woman',
      transcription: '| ˈwʊmən |',
      wordUa: 'жінка',
    },
    {
      src: 'words_1/man',
      wordAi: 'man',
      transcription: '| mæn |',
      wordUa: 'чоловік',
    },

    {
      src: 'words_1/girl',
      wordAi: 'girl',
      transcription: '| ɡɜːl |',
      wordUa: 'дівчинка',
    },
    {
      src: 'words_1/boy',
      wordAi: 'boy',
      transcription: '| ˌbɔɪ |',
      wordUa: 'хлопчик, хлопець',
    },
    {
      src: 'words_1/child',
      wordAi: 'child',
      transcription: '| tʃaɪld |',
      wordUa: 'дитина',
    },
    {
      src: 'words_1/children',
      wordAi: 'children',
      transcription: '| ˈtʃɪldrən |',
      wordUa: 'діти',
    },
  ],
  words_2: [
    {
      src: 'words_2/pencil',
      wordAi: 'pencil',
      transcription: '|ˈpens(ə)l|',
      wordUa: 'олівець',
    },
    {
      src: 'words_2/watch',
      wordAi: 'watch',
      transcription: '|wɒtʃ|',
      wordUa: 'годинник (наручний)',
    },
    {
      src: 'words_2/clock',
      wordAi: 'clock',
      transcription: '|klɒk|',
      wordUa: 'годинник',
    },
    {
      src: 'words_2/newspaper',
      wordAi: 'newspaper',
      transcription: '|ˈnjuːzpeɪpə|',
      wordUa: 'газета',
    },
    {
      src: 'words_2/businesscard',
      wordAi: 'business card',
      transcription: '|ˈbɪznəs| |kɑːd|',
      wordUa: 'візитка',
    },
    {
      src: 'words_2/glass',
      wordAi: 'glass',
      transcription: '|ɡlɑːs|',
      wordUa: 'склянка, скляний посуд',
    },
    {
      src: 'words_2/dictionary',
      wordAi: 'dictionary',
      transcription: '|ˈdɪkʃ(ə)n(ə)rɪ|',
      wordUa: 'словник',
    },
    {
      src: 'words_2/picture',
      wordAi: 'picture',
      transcription: '|ˈpɪktʃə|',
      wordUa: 'картина',
    },
    {
      src: 'words_2/creditcard',
      wordAi: 'credit card',
      transcription: '|ˈkredɪt| |kɑːd|',
      wordUa: 'кредитна карта',
    },
    {
      src: 'words_2/bag',
      wordAi: 'bag',
      transcription: '|bæɡ|',
      wordUa: 'сумка',
    },
    {
      src: 'words_2/pen',
      wordAi: 'pen',
      transcription: '|pen|',
      wordUa: 'ручка',
    },
    {
      src: 'words_2/table',
      wordAi: 'table',
      transcription: '|ˈteɪb(ə)l|',
      wordUa: 'стіл',
    },
    {
      src: 'words_2/box',
      wordAi: 'box',
      transcription: '|bɒks|',
      wordUa: 'коробка',
    },
    {
      src: 'words_2/cup',
      wordAi: 'cup',
      transcription: '|kʌp|',
      wordUa: 'чашка',
    },
    {
      src: 'words_2/notebook',
      wordAi: 'notebook',
      transcription: '|ˈnəʊtbʊk|',
      wordUa: 'блокнот',
    },
    {
      src: 'words_2/key',
      wordAi: 'key',
      transcription: '|kiː|',
      wordUa: 'ключ',
    },
    {
      src: 'words_2/laptop',
      wordAi: 'laptop',
      transcription: '|ˈlæptɒp|',
      wordUa: 'ноутбук',
    },
    {
      src: 'words_2/book',
      wordAi: 'book',
      transcription: '|bʊk|',
      wordUa: 'книга',
    },
    {
      src: 'words_2/chair',
      wordAi: 'chair',
      transcription: '|tʃeə|',
      wordUa: 'стул, крісло',
    },
  ],
  words_3: [
    {
      src: 'words_3/look',
      wordAi: 'Look',
      transcription: '|lʊk|',
      wordUa: 'Дивись!',
    },
    {
      src: 'words_3/listen',
      wordAi: 'Listen',
      transcription: '|ˈlɪs(ə)n|',
      wordUa: 'Слухай!',
    },
    {
      src: 'words_3/read',
      wordAi: 'Read',
      transcription: '|riːd|',
      wordUa: 'Читай!',
    },
    {
      src: 'words_3/repeat',
      wordAi: 'Repeat',
      transcription: '|rɪˈpiːt|',
      wordUa: 'Повторюй!',
    },
    {
      src: 'words_3/speak',
      wordAi: 'Speak',
      transcription: '|spiːk|',
      wordUa: 'Говори!',
    },
    {
      src: 'words_3/writedown',
      wordAi: 'Write down',
      transcription: '|ˈraɪt daʊn|',
      wordUa: 'Запиши!',
    },
    {
      src: 'words_3/spell',
      wordAi: 'Spell',
      transcription: '|spel|',
      wordUa: 'Вимови по буквах!<br>Напиши по буквах!',
    },
    {
      src: 'words_3/check',
      wordAi: 'Check',
      transcription: '|tʃek|',
      wordUa: 'Перевір!',
    },
    {
      src: 'words_3/askaquestion',
      wordAi: 'Ask a question',
      transcription: '',
      wordUa: 'Запитай!',
    },
    {
      src: 'words_3/answeraquestion',
      wordAi: 'Answer a question!',
      transcription: '',
      wordUa: 'Дай відповідь!',
    },
    {
      src: 'words_3/match',
      wordAi: 'Match',
      transcription: '|mætʃ|',
      wordUa: 'Поєднай!',
    },
    {
      src: 'words_3/choose',
      wordAi: 'Choose',
      transcription: '|tʃuːz|',
      wordUa: 'Обери!',
    },
    {
      src: 'words_3/fillinthegaps',
      wordAi: 'Fill in the gaps',
      transcription: '',
      wordUa: 'Заповни пропуски!',
    },
    {
      src: 'words_3/completethesentence',
      wordAi: 'Complete the sentence',
      transcription: '',
      wordUa: 'Закінчи речення!',
    },
    {
      src: 'words_3/workwithapartner',
      wordAi: 'Work with a partner!',
      transcription: '',
      wordUa: 'Працюй з партнером!',
    },
    {
      src: 'words_3/dothetask',
      wordAi: 'Do the task',
      transcription: '',
      wordUa: 'Виконай завдання!',
    },
    {
      src: 'words_3/tall',
      wordAi: 'tall',
      transcription: '|tɔːl|',
      wordUa: 'високий',
    },
    {
      src: 'words_3/short',
      wordAi: 'short',
      transcription: '|ʃɔːt|',
      wordUa: 'низький, короткий',
    },
    {
      src: 'words_3/long',
      wordAi: 'long',
      transcription: '|lɒŋ|',
      wordUa: 'довгий',
    },
    {
      src: 'words_3/cute',
      wordAi: 'cute',
      transcription: '|kjuːt|',
      wordUa: 'гарненький',
    },
    {
      src: 'words_3/easy',
      wordAi: 'easy',
      transcription: '|ˈiːzɪ|',
      wordUa: 'легкий',
    },
    {
      src: 'words_3/difficult',
      wordAi: 'difficult',
      transcription: '|ˈdɪfɪk(ə)lt|',
      wordUa: 'складний',
    },
    {
      src: 'words_3/big',
      wordAi: 'big',
      transcription: '|bɪɡ|',
      wordUa: 'великий',
    },
    {
      src: 'words_3/small',
      wordAi: 'small',
      transcription: '|smɔːl|',
      wordUa: 'маленький',
    },
    {
      src: 'words_3/interesting',
      wordAi: 'interesting',
      transcription: '|ˈɪnt(ə)rɪstɪŋ|',
      wordUa: 'цікавий',
    },
    {
      src: 'words_3/smart',
      wordAi: 'smart',
      transcription: '|smɑːt|',
      wordUa: 'розумний',
    },
    {
      src: 'words_3/happy',
      wordAi: 'happy',
      transcription: '|ˈhæpɪ|',
      wordUa: 'щасливий',
    },
    {
      src: 'words_3/sad',
      wordAi: 'sad',
      transcription: '|sæd|',
      wordUa: 'сумний',
    },
  ],
  words_4: [
    { src: 'words_4/bag', wordAi: 'bag', transcription: '', wordUa: 'сумка' },
    { src: 'words_4/camera', wordAi: 'camera', transcription: '', wordUa: 'фотокамера' },
    { src: 'words_4/charger', wordAi: 'charger', transcription: '', wordUa: 'зарядний пристрій' },
    { src: 'words_4/cup', wordAi: 'cup', transcription: '', wordUa: 'чашка' },
    { src: 'words_4/key', wordAi: 'key', transcription: '', wordUa: 'ключ' },
    { src: 'words_4/laptop', wordAi: 'laptop', transcription: '', wordUa: 'ноутбук' },
    { src: 'words_4/lipstick', wordAi: 'lipstick', transcription: '', wordUa: 'помада для губ' },
    { src: 'words_4/money', wordAi: 'money', transcription: '', wordUa: 'гроші' },
    { src: 'words_4/passport', wordAi: 'passport', transcription: '', wordUa: 'паспорт' },
    { src: 'words_4/pen', wordAi: 'pen', transcription: '', wordUa: 'ручка' },
    { src: 'words_4/purse', wordAi: 'purse', transcription: '', wordUa: 'дамська сумочка' },
    { src: 'words_4/speakers', wordAi: 'speakers', transcription: '', wordUa: 'колонки' },
    { src: 'words_4/tablet', wordAi: 'tablet', transcription: '', wordUa: 'планшет' },
    { src: 'words_4/tv', wordAi: 'TV', transcription: '', wordUa: 'телевізор' },
    { src: 'words_4/t-shirt', wordAi: 'T-shirt', transcription: '', wordUa: 'футболка' },
    { src: 'words_4/umbrella', wordAi: 'umbrella', transcription: '', wordUa: 'парасолька' },
    { src: 'words_4/wallet', wordAi: 'wallet', transcription: '', wordUa: 'гаманець' },
    { src: 'words_4/watch', wordAi: 'watch', transcription: '', wordUa: 'наручний годинник' },
    { src: 'words_4/earphones', wordAi: 'earphones', transcription: '', wordUa: 'навушники' },
    { src: 'words_4/headphones', wordAi: 'headphones', transcription: '', wordUa: 'навушники' },
    { src: 'words_4/jeans', wordAi: 'jeans', transcription: '', wordUa: 'джинси' },
  ],
  words_5: [
    { src: 'words_5/car', wordAi: 'car', transcription: '', wordUa: 'машина, автівка' },
    { src: 'words_5/window', wordAi: 'window', transcription: '', wordUa: 'вікно' },
    { src: 'words_5/door', wordAi: 'door', transcription: '', wordUa: 'двері' },
    { src: 'words_5/roof', wordAi: 'roof', transcription: '', wordUa: 'дах' },
    { src: 'words_5/radio', wordAi: 'radio', transcription: '', wordUa: 'радіо' },
    { src: 'words_5/table', wordAi: 'table', transcription: '', wordUa: 'стіл' },
    { src: 'words_5/box', wordAi: 'box', transcription: '', wordUa: 'коробка' },
    { src: 'words_5/brush', wordAi: 'brush', transcription: '', wordUa: 'пензель, пензлик' },
    { src: 'words_5/bus', wordAi: 'bus', transcription: '', wordUa: 'автобус' },
    { src: 'words_5/baby', wordAi: 'baby', transcription: '', wordUa: 'дитина, дитинка' },
    { src: 'words_5/family', wordAi: 'family', transcription: '', wordUa: "родина, сім'я" },
    { src: 'words_5/dress', wordAi: 'dress', transcription: '', wordUa: 'сукня' },
    {
      src: 'words_5/child',
      wordAi: 'child',
      transcription: '',
      wordUa: 'дитина',
    },
    {
      src: 'words_5/children',
      wordAi: 'children',
      transcription: '',
      wordUa: 'діти',
    },
    {
      src: 'words_5/man',
      wordAi: 'man',
      transcription: '',
      wordUa: 'чоловік',
    },
    {
      src: 'words_5/men',
      wordAi: 'manmen',
      transcription: '',
      wordUa: 'чоловіки',
    },
    {
      src: 'words_5/woman',
      wordAi: 'woman',
      transcription: '',
      wordUa: 'жінка',
    },
    {
      src: 'words_5/women',
      wordAi: 'women',
      transcription: '',
      wordUa: 'жінки',
    },
    {
      src: 'words_5/tooth',
      wordAi: 'tooth',
      transcription: '',
      wordUa: 'зуб',
    },
    {
      src: 'words_5/teeth',
      wordAi: 'teeth',
      transcription: '',
      wordUa: 'зуби',
    },
    {
      src: 'words_5/foot',
      wordAi: 'foot',
      transcription: '',
      wordUa: 'нога',
    },
    {
      src: 'words_5/feet',
      wordAi: 'feet',
      transcription: '',
      wordUa: 'ноги',
    },
    {
      src: 'words_5/goose',
      wordAi: 'goose',
      transcription: '',
      wordUa: 'гуска',
    },
    {
      src: 'words_5/geese',
      wordAi: 'geese',
      transcription: '',
      wordUa: 'гусі',
    },
    {
      src: 'words_5/mice',
      wordAi: 'mice',
      transcription: '',
      wordUa: 'миші',
    },
    {
      src: 'words_5/mouse',
      wordAi: 'mouse',
      transcription: '',
      wordUa: 'миша',
    },
    {
      src: 'words_5/person',
      wordAi: 'person',
      transcription: '',
      wordUa: 'людина',
    },
    {
      src: 'words_5/people',
      wordAi: 'people',
      transcription: '',
      wordUa: 'люди',
    },
    {
      src: 'words_5/sheep',
      wordAi: 'sheep',
      transcription: '',
      wordUa: 'вівця - вівці',
    },
    {
      src: 'words_5/deer',
      wordAi: 'deer',
      transcription: '',
      wordUa: 'олень - олені',
    },
    {
      src: 'words_5/wolf',
      wordAi: 'wolf',
      transcription: '',
      wordUa: 'вовк',
    },
    {
      src: 'words_5/wolves',
      wordAi: 'wolves',
      transcription: '|wʊlvz|',
      wordUa: 'вовки',
    },
    {
      src: 'words_5/leaf',
      wordAi: 'leaf',
      transcription: '',
      wordUa: 'листок',
    },
    {
      src: 'words_5/leaves',
      wordAi: 'leaves',
      transcription: '',
      wordUa: 'листя',
    },
    {
      src: 'words_5/wife',
      wordAi: 'wife',
      transcription: '',
      wordUa: 'дружина',
    },
    {
      src: 'words_5/wives',
      wordAi: 'wives',
      transcription: '',
      wordUa: 'дружини',
    },
    {
      src: 'words_5/potato',
      wordAi: 'potato',
      transcription: '',
      wordUa: 'картоплина',
    },
    {
      src: 'words_5/potatoes',
      wordAi: 'potatoes',
      transcription: '',
      wordUa: 'картопля',
    },
    {
      src: 'words_5/tomato',
      wordAi: 'tomato',
      transcription: '',
      wordUa: 'помідор',
    },
    {
      src: 'words_5/tomatoes',
      wordAi: 'tomatoes',
      transcription: '',
      wordUa: 'помідори',
    },
    {
      src: 'words_5/hero',
      wordAi: 'hero',
      transcription: '',
      wordUa: 'герой',
    },
    {
      src: 'words_5/heroes',
      wordAi: 'heroes',
      transcription: '',
      wordUa: 'герої',
    },
  ],
  words_6: [
    { src: 'words_6/desk', wordAi: 'desk', transcription: '', wordUa: 'письмовий стіл' },
    { src: 'words_6/shoe', wordAi: 'shoe', transcription: '', wordUa: 'черевик' },
    { src: 'words_6/zoo', wordAi: 'zoo', transcription: '', wordUa: 'зоопарк' },
    { src: 'words_6/cup', wordAi: 'cup', transcription: '', wordUa: 'чашка' },
    { src: 'words_6/cliff', wordAi: 'cliff', transcription: '', wordUa: 'скеля' },
    { src: 'words_6/kiss', wordAi: 'kiss', transcription: '', wordUa: 'поцілунок' },
    { src: 'words_6/computer', wordAi: 'computer', transcription: '', wordUa: "комп'ютер" },
    { src: 'words_6/sandwich', wordAi: 'sandwich', transcription: '', wordUa: 'сендвіч' },
    { src: 'words_6/strawberry', wordAi: 'strawberry', transcription: '', wordUa: 'полуниця' },
    { src: 'words_6/bush', wordAi: 'bush', transcription: '', wordUa: 'кущ' },
    { src: 'words_6/country', wordAi: 'country', transcription: '', wordUa: 'країна' },
    { src: 'words_6/vegetable', wordAi: 'vegetable', transcription: '', wordUa: 'овоч' },
    { src: 'words_6/house', wordAi: 'house', transcription: '', wordUa: 'будинок' },
    { src: 'words_6/expensive', wordAi: 'expensive', transcription: '', wordUa: 'дорогий' },
  ],
  words_7: [
    { src: 'words_7/family', wordAi: 'family', transcription: '', wordUa: "сім'я, родина" },
    { src: 'words_7/parents', wordAi: 'parents', transcription: '', wordUa: 'батьки' },
    { src: 'words_7/mother', wordAi: 'mother', transcription: '', wordUa: 'мати' },
    { src: 'words_7/mum', wordAi: 'mum', transcription: '', wordUa: 'мама' },
    { src: 'words_7/father', wordAi: 'father', transcription: '', wordUa: 'батько' },
    { src: 'words_7/dad', wordAi: 'dad', transcription: '', wordUa: 'тато' },
    { src: 'words_7/child', wordAi: 'child', transcription: '', wordUa: 'дитина' },
    { src: 'words_7/children', wordAi: 'children', transcription: '', wordUa: 'діти' },
    { src: 'words_7/kid', wordAi: 'kid', transcription: '', wordUa: 'дитина' },
    { src: 'words_7/kids', wordAi: 'kids', transcription: '', wordUa: 'діти' },
    { src: 'words_7/daughter', wordAi: 'daughter', transcription: '', wordUa: 'дочка' },
    { src: 'words_7/son', wordAi: 'son', transcription: '', wordUa: 'син' },
    {
      src: 'words_7/sibling',
      wordAi: 'sibling',
      transcription: '',
      wordUa: 'рідний брат або сестра',
    },
    { src: 'words_7/brother', wordAi: 'brother', transcription: '', wordUa: 'брат' },
    { src: 'words_7/sister', wordAi: 'sister', transcription: '', wordUa: 'сестра' },
    { src: 'words_7/grandmother', wordAi: 'grandmother', transcription: '', wordUa: 'бабуся' },
    { src: 'words_7/grandma', wordAi: 'grandma', transcription: '', wordUa: 'бабуся (лагідно)' },
    { src: 'words_7/grandfather', wordAi: 'grandfather', transcription: '', wordUa: 'дідусь' },
    { src: 'words_7/grandpa', wordAi: 'grandpa', transcription: '', wordUa: 'дідусь (лагідно)' },
    { src: 'words_7/granddaughter', wordAi: 'granddaughter', transcription: '', wordUa: 'онука' },
    { src: 'words_7/grandson', wordAi: 'grandson', transcription: '', wordUa: 'онук' },
    {
      src: 'words_7/aunt',
      wordAi: 'aunt',
      transcription: '',
      wordUa: "mother's or father's sister\nтітка",
    },
    {
      src: 'words_7/uncle',
      wordAi: 'uncle',
      transcription: '',
      wordUa: "mother's or father's brother\nдядько",
    },
    {
      src: 'words_7/cousin',
      wordAi: 'cousin',
      transcription: '',
      wordUa: "aunt's or uncle's son or daughter\nдвоюрідний брат або двоюрідна сестра",
    },
    {
      src: 'words_7/nephew',
      wordAi: 'nephew',
      transcription: '',
      wordUa: "brother's or sister's son\nплемінник",
    },
    {
      src: 'words_7/niece',
      wordAi: 'niece',
      transcription: '',
      wordUa: "brother's or sister's daughter\nплемінниця",
    },
    { src: 'words_7/girlfriend', wordAi: 'girlfriend', transcription: '', wordUa: 'дівчина' },
    { src: 'words_7/boyfriend', wordAi: 'boyfriend', transcription: '', wordUa: 'хлопець' },
    { src: 'words_7/wife', wordAi: 'wife', transcription: '', wordUa: 'дружина' },
    { src: 'words_7/husband', wordAi: 'husband', transcription: '', wordUa: 'чоловік' },
    { src: 'words_7/married', wordAi: 'married', transcription: '', wordUa: 'одружений / заміжня' },
    {
      src: 'words_7/divorced',
      wordAi: 'divorced',
      transcription: '',
      wordUa: 'розлучений / розлучена',
    },
    {
      src: 'words_7/single',
      wordAi: 'single',
      transcription: '',
      wordUa: 'неодружений / незаміжня',
    },
  ],
  words_8: [
    { src: 'words_8/bag', wordAi: 'bag', transcription: '', wordUa: 'сумка' },
    { src: 'words_8/book', wordAi: 'book', transcription: '', wordUa: 'книга' },
    { src: 'words_8/camera', wordAi: 'camera', transcription: '', wordUa: 'фотокамера' },
    {
      src: 'words_8/cellphone',
      wordAi: 'cell phone',
      transcription: '',
      wordUa: 'сотовий телефон',
    },
    {
      src: 'words_8/mobilephone',
      wordAi: 'mobile phone',
      transcription: '',
      wordUa: 'мобільний телефон',
    },
    { src: 'words_8/smartphone', wordAi: 'smartphone', transcription: '', wordUa: 'смартфон' },
    { src: 'words_8/charger', wordAi: 'charger', transcription: '', wordUa: 'зарядний пристрій' },
    {
      src: 'words_8/creditcard',
      wordAi: 'credit card',
      transcription: '',
      wordUa: 'кредитна карта',
    },
    { src: 'words_8/cup', wordAi: 'cup', transcription: '', wordUa: 'чашка' },
    { src: 'words_8/door', wordAi: 'door', transcription: '', wordUa: 'двері' },
    { src: 'words_8/earphones', wordAi: 'earphones', transcription: '', wordUa: 'навушники' },
    { src: 'words_8/idcard', wordAi: 'ID card', transcription: '', wordUa: 'ID-картка' },
    { src: 'words_8/ipad', wordAi: 'iPad', transcription: '', wordUa: 'айпад' },
    { src: 'words_8/key', wordAi: 'key', transcription: '', wordUa: 'ключ' },
    { src: 'words_8/laptop', wordAi: 'laptop', transcription: '', wordUa: 'ноутбук' },
    { src: 'words_8/lipstick', wordAi: 'lipstick', transcription: '', wordUa: 'помада для губ' },
    { src: 'words_8/money', wordAi: 'money', transcription: '', wordUa: 'гроші' },
    { src: 'words_8/passport', wordAi: 'passport', transcription: '', wordUa: 'паспорт' },
    { src: 'words_8/purse', wordAi: 'purse', transcription: '', wordUa: 'дамська сумочка' },
    { src: 'words_8/speakers', wordAi: 'speakers', transcription: '', wordUa: 'колонки' },
    { src: 'words_8/tablet', wordAi: 'tablet', transcription: '', wordUa: 'планшет' },
    {
      src: 'words_8/television(tv)',
      wordAi: 'television (TV)',
      transcription: '',
      wordUa: 'телевізор',
    },
    { src: 'words_8/t-shirt', wordAi: 'T-shirt', transcription: '', wordUa: 'футболка' },
    { src: 'words_8/umbrella', wordAi: 'umbrella', transcription: '', wordUa: 'парасолька' },
    { src: 'words_8/wallet', wordAi: 'wallet', transcription: '', wordUa: 'гаманець' },
    { src: 'words_8/watch', wordAi: 'watch', transcription: '', wordUa: 'наручний годинник' },
    { src: 'words_8/window', wordAi: 'window', transcription: '', wordUa: 'вікно' },
    { src: 'words_8/scooter', wordAi: 'scooter', transcription: '', wordUa: 'самокат, мопед' },
    { src: 'words_8/drone', wordAi: 'drone', transcription: '', wordUa: 'дрон' },
    { src: 'words_8/bottle', wordAi: 'bottle', transcription: '', wordUa: 'бутилка' },
    { src: 'words_8/country', wordAi: 'country', transcription: '', wordUa: 'країна' },
    {
      src: 'words_8/nationality',
      wordAi: 'nationality',
      transcription: '',
      wordUa: 'національність',
    },
    { src: 'words_8/canada', wordAi: 'Canada', transcription: '', wordUa: 'Канада' },
    {
      src: 'words_8/canadian',
      wordAi: 'Canadian',
      transcription: '',
      wordUa: 'someone who is from Canada',
    },
    { src: 'words_8/china', wordAi: 'China', transcription: '', wordUa: 'Китай' },
    {
      src: 'words_8/chinese',
      wordAi: 'Chinese',
      transcription: '',
      wordUa: 'someone who is from China',
    },
    { src: 'words_8/france', wordAi: 'France', transcription: '', wordUa: 'Франція' },
    {
      src: 'words_8/french',
      wordAi: 'French',
      transcription: '',
      wordUa: 'someone who is from France',
    },
    { src: 'words_8/germany', wordAi: 'Germany', transcription: '', wordUa: 'Німеччина' },
    {
      src: 'words_8/german',
      wordAi: 'German',
      transcription: '',
      wordUa: 'someone who is from Germany',
    },
    {
      src: 'words_8/greatbritain',
      wordAi: 'Great Britain',
      transcription: '',
      wordUa: 'Великобританія',
    },
    {
      src: 'words_8/british',
      wordAi: 'British',
      transcription: '',
      wordUa: 'someone who comes from Great Britain',
    },
    {
      src: 'words_8/theusa',
      wordAi: 'the USA',
      transcription: '',
      wordUa: 'Сполучені Штати Америки',
    },
    {
      src: 'words_8/american',
      wordAi: 'American',
      transcription: '',
      wordUa: 'someone who is from the United States of America',
    },
    { src: 'words_8/poland', wordAi: 'Poland', transcription: '', wordUa: 'Польща' },
    {
      src: 'words_8/polish',
      wordAi: 'Polish',
      transcription: '',
      wordUa: 'someone who is from Poland',
    },
    { src: 'words_8/italy', wordAi: 'Italy', transcription: '', wordUa: 'Італія' },
    {
      src: 'words_8/italian',
      wordAi: 'Italian',
      transcription: '',
      wordUa: 'someone who is from Italy',
    },
    { src: 'words_8/ukraine', wordAi: 'Ukraine', transcription: '', wordUa: 'Україна' },
    {
      src: 'words_8/ukrainian',
      wordAi: 'Ukrainian',
      transcription: '',
      wordUa: 'someone who is from Ukraine',
    },
    {
      src: 'words_8/whereareyoufrom',
      wordAi: 'Where are you from?',
      transcription: '',
      wordUa: 'Звідки ви?',
    },
  ],
  words_9: [
    { src: 'words_9/one', wordAi: 'one', transcription: '', wordUa: '' },
    { src: 'words_9/two', wordAi: 'two', transcription: '', wordUa: '' },
    { src: 'words_9/three', wordAi: 'three', transcription: '', wordUa: '' },
    { src: 'words_9/four', wordAi: 'four', transcription: '', wordUa: '' },
    { src: 'words_9/five', wordAi: 'five', transcription: '', wordUa: '' },
    { src: 'words_9/six', wordAi: 'six', transcription: '', wordUa: '' },
    { src: 'words_9/seven', wordAi: 'seven', transcription: '', wordUa: '' },
    { src: 'words_9/eight', wordAi: 'eight', transcription: '', wordUa: '' },
    { src: 'words_9/nine', wordAi: 'nine', transcription: '', wordUa: '' },
    { src: 'words_9/ten', wordAi: 'ten', transcription: '', wordUa: '' },
    { src: 'words_9/eleven', wordAi: 'eleven', transcription: '', wordUa: '' },
    { src: 'words_9/twelve', wordAi: 'twelve', transcription: '', wordUa: '' },
    { src: 'words_9/thirteen', wordAi: 'thirteen', transcription: '', wordUa: '' },
    { src: 'words_9/fourteen', wordAi: 'fourteen', transcription: '', wordUa: '' },
    { src: 'words_9/fifteen', wordAi: 'fifteen', transcription: '', wordUa: '' },
    { src: 'words_9/sixteen', wordAi: 'sixteen', transcription: '', wordUa: '' },
    { src: 'words_9/seventeen', wordAi: 'seventeen', transcription: '', wordUa: '' },
    { src: 'words_9/eighteen', wordAi: 'eighteen', transcription: '', wordUa: '' },
    { src: 'words_9/nineteen', wordAi: 'nineteen', transcription: '', wordUa: '' },
    { src: 'words_9/twenty', wordAi: 'twenty', transcription: '', wordUa: '' },
    { src: 'words_9/twenty-one', wordAi: 'twenty-one', transcription: '', wordUa: '' },
    { src: 'words_9/twenty-two', wordAi: 'twenty-two', transcription: '', wordUa: '' },
    { src: 'words_9/twenty-three', wordAi: 'twenty-three', transcription: '', wordUa: '' },
    { src: 'words_9/twenty-four', wordAi: 'twenty-four', transcription: '', wordUa: '' },
    { src: 'words_9/twenty-five', wordAi: 'twenty-five', transcription: '', wordUa: '' },
    { src: 'words_9/twenty-six', wordAi: 'twenty-six', transcription: '', wordUa: '' },
    { src: 'words_9/twenty-seven', wordAi: 'twenty-seven', transcription: '', wordUa: '' },
    { src: 'words_9/twenty-eight', wordAi: 'twenty-eight', transcription: '', wordUa: '' },
    { src: 'words_9/twenty-nine', wordAi: 'twenty-nine', transcription: '', wordUa: '' },
    { src: 'words_9/thirty', wordAi: 'thirty', transcription: '', wordUa: '' },
    { src: 'words_9/forty', wordAi: 'forty', transcription: '', wordUa: '' },
    { src: 'words_9/fifty', wordAi: 'fifty', transcription: '', wordUa: '' },
    { src: 'words_9/sixty', wordAi: 'sixty', transcription: '', wordUa: '' },
    { src: 'words_9/seventy', wordAi: 'seventy', transcription: '', wordUa: '' },
    { src: 'words_9/eighty', wordAi: 'eighty', transcription: '', wordUa: '' },
    { src: 'words_9/ninety', wordAi: 'ninety', transcription: '', wordUa: '' },
    {
      src: 'words_9/ahundred',
      wordAi: 'a hundred',
      transcription: '',
      wordUa: '',
    },
    {
      src: 'words_9/onehundred',
      wordAi: 'one hundred',
      transcription: '',
      wordUa: '',
    },
    {
      src: 'words_9/athousand',
      wordAi: 'a thousand',
      transcription: '',
      wordUa: '',
    },
    {
      src: 'words_9/onethousand',
      wordAi: 'one thousand',
      transcription: '',
      wordUa: '',
    },
    {
      src: 'words_9/howoldareyou',
      wordAi: 'How old are you?',
      transcription: '',
      wordUa: 'Скільки вам років?',
    },
    {
      src: 'words_9/im22',
      wordAi: "I'm 22",
      transcription: '',
      wordUa: 'Мені ... (22)',
    },
    {
      src: 'words_9/im22yearsold',
      wordAi: "I'm 22 years old",
      transcription: '',
      wordUa: 'Мені ... (22) роки',
    },
  ],
  words_10: [
    { src: 'words_10/day', wordAi: 'day', transcription: '', wordUa: 'день' },
    { src: 'words_10/month', wordAi: 'month', transcription: '', wordUa: 'місяць' },
    { src: 'words_10/january', wordAi: 'January', transcription: '', wordUa: 'січень' },
    { src: 'words_10/february', wordAi: 'February', transcription: '', wordUa: 'лютий' },
    { src: 'words_10/march', wordAi: 'March', transcription: '', wordUa: 'березень' },
    { src: 'words_10/april', wordAi: 'April', transcription: '', wordUa: 'квітень' },
    { src: 'words_10/may', wordAi: 'May', transcription: '', wordUa: 'травень' },
    { src: 'words_10/june', wordAi: 'June', transcription: '', wordUa: 'червень' },
    { src: 'words_10/july', wordAi: 'July', transcription: '', wordUa: 'липень' },
    { src: 'words_10/august', wordAi: 'August', transcription: '', wordUa: 'серпень' },
    { src: 'words_10/september', wordAi: 'September', transcription: '', wordUa: 'вересень' },
    { src: 'words_10/october', wordAi: 'October', transcription: '', wordUa: 'жовтень' },
    { src: 'words_10/november', wordAi: 'November', transcription: '', wordUa: 'листопад' },
    { src: 'words_10/december', wordAi: 'December', transcription: '', wordUa: 'грудень' },
    { src: 'words_10/inmay', wordAi: 'in May', transcription: '', wordUa: 'у травні' },
    { src: 'words_10/monday', wordAi: 'Monday', transcription: '', wordUa: 'понеділок' },
    { src: 'words_10/tuesday', wordAi: 'Tuesday', transcription: '', wordUa: 'вівторок' },
    { src: 'words_10/wednesday', wordAi: 'Wednesday', transcription: '', wordUa: 'середа' },
    { src: 'words_10/thursday', wordAi: 'Thursday', transcription: '', wordUa: 'четвер' },
    { src: 'words_10/friday', wordAi: 'Friday', transcription: '', wordUa: "п'ятниця" },
    { src: 'words_10/saturday', wordAi: 'Saturday', transcription: '', wordUa: 'субота' },
    { src: 'words_10/sunday', wordAi: 'Sunday', transcription: '', wordUa: 'неділя' },
    { src: 'words_10/onmonday', wordAi: 'on Monday', transcription: '', wordUa: 'в понеділок' },
  ],
  words_11: [
    { src: 'words_11/armchair', wordAi: 'armchair', transcription: '', wordUa: 'крісло' },
    { src: 'words_11/bed', wordAi: 'bed', transcription: '', wordUa: 'ліжко' },
    { src: 'words_11/chair', wordAi: 'chair', transcription: '', wordUa: 'стілець' },
    {
      src: 'words_11/coffeetable',
      wordAi: 'coffee table',
      transcription: '',
      wordUa: 'журнальний столик',
    },
    { src: 'words_11/cupboard', wordAi: 'cupboard', transcription: '', wordUa: 'навісна шафа' },
    { src: 'words_11/fridge', wordAi: 'fridge', transcription: '', wordUa: 'холодильник' },
    { src: 'words_11/lamp', wordAi: 'lamp', transcription: '', wordUa: 'лампа' },
    {
      src: 'words_11/microwave',
      wordAi: 'microwave',
      transcription: '',
      wordUa: 'мікрохвильова піч',
    },
    { src: 'words_11/shelf', wordAi: 'shelf', transcription: '', wordUa: 'полиця' },
    { src: 'words_11/sofa', wordAi: 'sofa', transcription: '', wordUa: 'диван' },
    { src: 'words_11/table', wordAi: 'table', transcription: '', wordUa: 'стіл' },
    { src: 'words_11/tv', wordAi: 'TV', transcription: '', wordUa: 'телевізор' },
    { src: 'words_11/wardrobe', wordAi: 'wardrobe', transcription: '', wordUa: 'шафа' },
    { src: 'words_11/wi-fi', wordAi: 'Wi-Fi', transcription: '', wordUa: '' },
    { src: 'words_11/window', wordAi: 'window', transcription: '', wordUa: 'вікно' },
    { src: 'words_11/lift', wordAi: 'lift', transcription: '', wordUa: 'ліфт' },
    { src: 'words_11/balcony', wordAi: 'balcony', transcription: '', wordUa: 'балкон' },
    { src: 'words_11/parking', wordAi: 'parking', transcription: '', wordUa: 'паркінг' },
    { src: 'words_11/restaurant', wordAi: 'restaurant', transcription: '', wordUa: 'ресторан' },
    { src: 'words_11/shop', wordAi: 'shop', transcription: '', wordUa: 'магазин, крамниця' },
    { src: 'words_11/wall', wordAi: 'wall', transcription: '', wordUa: 'стіна' },
    { src: 'words_11/home', wordAi: 'home', transcription: '', wordUa: 'дім' },
    { src: 'words_11/apartment', wordAi: 'apartment', transcription: '', wordUa: 'квартира' },
    {
      src: 'words_11/inthecitycenter',
      wordAi: 'in the city center',
      transcription: '',
      wordUa: 'в центрі міста',
    },
    { src: 'words_11/kitchen', wordAi: 'kitchen', transcription: '', wordUa: 'кухня' },
    { src: 'words_11/bedroom', wordAi: 'bedroom', transcription: '', wordUa: 'спальня' },
    { src: 'words_11/in', wordAi: 'in', transcription: '', wordUa: 'в' },
    { src: 'words_11/on', wordAi: 'on', transcription: '', wordUa: 'на' },
    { src: 'words_11/under', wordAi: 'under', transcription: '', wordUa: 'під' },
    { src: 'words_11/nextto', wordAi: 'next to', transcription: '', wordUa: 'біля, поруч' },
    {
      src: 'words_11/infrontof',
      wordAi: 'in front of',
      transcription: '',
      wordUa: 'попереду, перед',
    },
    { src: 'words_11/behind', wordAi: 'behind', transcription: '', wordUa: 'позаду, за' },
    { src: 'words_11/between', wordAi: 'between', transcription: '', wordUa: 'між' },
  ],
  words_12: [
    { src: 'words_12/house', wordAi: 'house', transcription: '', wordUa: 'будинок' },
    { src: 'words_12/bathroom', wordAi: 'bathroom', transcription: '', wordUa: 'ванна кімната' },
    { src: 'words_12/bedroom', wordAi: 'bedroom', transcription: '', wordUa: 'спальня' },
    {
      src: 'words_12/diningroom',
      wordAi: 'dining room',
      transcription: '',
      wordUa: 'столова кімната',
    },
    { src: 'words_12/kitchen', wordAi: 'kitchen', transcription: '', wordUa: 'кухня' },
    { src: 'words_12/livingroom', wordAi: 'living room', transcription: '', wordUa: 'вітальня' },
    { src: 'words_12/study', wordAi: 'study', transcription: '', wordUa: 'кабінет' },
    { src: 'words_12/garage', wordAi: 'garage', transcription: '', wordUa: 'гараж' },
    { src: 'words_12/garden', wordAi: 'garden', transcription: '', wordUa: 'сад' },
    { src: 'words_12/modern', wordAi: 'modern', transcription: '', wordUa: 'сучасний' },
    {
      src: 'words_12/comfortable',
      wordAi: 'comfortable',
      transcription: '',
      wordUa: 'зручний, комфортабельний, затишний',
    },
    {
      src: 'words_12/perfect',
      wordAi: 'perfect',
      transcription: '',
      wordUa: 'досконалий, ідеальний',
    },
  ],
  words_13: [
    { src: 'words_13/cook', wordAi: 'cook', transcription: '', wordUa: 'готувати' },
    { src: 'words_13/dance', wordAi: 'dance', transcription: '', wordUa: 'танцювати' },
    { src: 'words_13/perfect', wordAi: 'perfect', transcription: '', wordUa: 'ідеальний' },
    { src: 'words_13/read', wordAi: 'read', transcription: '', wordUa: 'читати' },
    {
      src: 'words_13/rideabicycle',
      wordAi: 'ride a bicycle',
      transcription: '',
      wordUa: 'кататися на велосипеді',
    },
    { src: 'words_13/run', wordAi: 'run', transcription: '', wordUa: 'бігати' },
    { src: 'words_13/swim', wordAi: 'swim', transcription: '', wordUa: 'плавати' },
    { src: 'words_13/ski', wordAi: 'ski', transcription: '', wordUa: 'кататися на лижах' },
    { src: 'words_13/sing', wordAi: 'sing', transcription: '', wordUa: 'співати' },
    { src: 'words_13/speak', wordAi: 'speak', transcription: '', wordUa: 'говорити' },
    { src: 'words_13/write', wordAi: 'write', transcription: '', wordUa: 'писати' },
    { src: 'words_13/drink', wordAi: 'drink', transcription: '', wordUa: 'пити' },
    {
      src: 'words_13/drive',
      wordAi: 'drive',
      transcription: '',
      wordUa: 'водити, керувати автівкою',
    },
    { src: 'words_13/paint', wordAi: 'paint', transcription: '', wordUa: 'малювати' },
    {
      src: 'words_13/playfootball',
      wordAi: 'play football',
      transcription: '',
      wordUa: 'грати у футбол',
    },
    {
      src: 'words_13/playtheguitar',
      wordAi: 'play the guitar',
      transcription: '',
      wordUa: 'грати на гітарі',
    },
    {
      src: 'words_13/usephotoshop',
      wordAi: 'use Photoshop',
      transcription: '',
      wordUa: 'користуватися фотошопом',
    },
    { src: 'words_13/amusician', wordAi: 'a musician', transcription: '', wordUa: 'музикант' },
    { src: 'words_13/acook', wordAi: 'a cook', transcription: '', wordUa: 'кухар' },
    {
      src: 'words_13/athletic',
      wordAi: 'athletic',
      transcription: '',
      wordUa: 'спортивний, атлетичний',
    },
    {
      src: 'words_13/excellent',
      wordAi: 'excellent',
      transcription: '',
      wordUa: 'відмінний, чудовий',
    },
  ],
  words_14: [
    {
      src: 'words_14/canyoucook',
      wordAi: 'Can you cook?',
      transcription: '',
      wordUa: 'Ви вмієте готувати? / Ти вмієш готувати?',
    },
    {
      src: 'words_14/icancook',
      wordAi: 'I can cook',
      transcription: '',
      wordUa: 'Я вмію готувати.',
    },
    {
      src: 'words_14/icantcookamebe',
      wordAi: "I can't cook",
      transcription: '',
      wordUa: 'Я не вмію готувати.',
    },
    { src: 'words_14/boss', wordAi: 'boss', transcription: '', wordUa: 'бос' },
    { src: 'words_14/secretary', wordAi: 'secretary', transcription: '', wordUa: 'секретар' },
    {
      src: 'words_14/international',
      wordAi: 'international',
      transcription: '',
      wordUa: 'міжнародний',
    },
  ],
  words_15: [
    { src: 'words_15/cheap', wordAi: 'cheap', transcription: '', wordUa: 'дешевий' },
    { src: 'words_15/expensive', wordAi: 'expensive', transcription: '', wordUa: 'дорогий' },
    { src: 'words_15/money', wordAi: 'money', transcription: '', wordUa: 'гроші' },
    { src: 'words_15/price', wordAi: 'price', transcription: '', wordUa: 'ціна' },
    { src: 'words_15/hotel', wordAi: 'hotel', transcription: '', wordUa: 'готель' },
    { src: 'words_15/museum', wordAi: 'museum', transcription: '', wordUa: 'музей' },
    { src: 'words_15/monument', wordAi: 'monument', transcription: '', wordUa: "пам'ятник" },
    { src: 'words_15/beach', wordAi: 'beach', transcription: '', wordUa: 'пляж' },
    { src: 'words_15/prison', wordAi: 'prison', transcription: '', wordUa: "в'язниця" },
    { src: 'words_15/tour', wordAi: 'tour', transcription: '', wordUa: 'тур, екскурсія' },
    { src: 'words_15/weather', wordAi: 'weather', transcription: '', wordUa: 'погода' },
    {
      src: 'words_15/fantastic',
      wordAi: 'fantastic',
      transcription: '',
      wordUa: 'фантастичний, неймовірний',
    },
    { src: 'words_15/delicious', wordAi: 'delicious', transcription: '', wordUa: 'дуже смачний' },
    {
      src: 'words_15/beautiful',
      wordAi: 'beautiful',
      transcription: '',
      wordUa: 'вродливий, гарний',
    },
    {
      src: 'words_15/fashionable',
      wordAi: 'fashionable',
      transcription: '',
      wordUa: 'модний, фешенебельний',
    },
    { src: 'words_15/famous', wordAi: 'famous', transcription: '', wordUa: 'відомий' },
    { src: 'words_15/awesome', wordAi: 'awesome', transcription: '', wordUa: 'крутий, дивовижний' },
  ],
};
